let QUIZ = [
    {id: cuid(),
    question: "How do tigers live?",
    correctAnswer: "Alone",
    answers: ["In a pride", "Alone", "With their mates", "With their relatives"],
    feedback: "Tigers are solitary animals, with the exception of mothers and their cubs."},
    {id: cuid(),
    question: "Which of the following is a tiger incapable of?",
    correctAnswer: "Running long distances",
    answers: ["Climbing tall trees", "Swimming through the river",  "Running long distances", "Leaping great heights"],
    feedback: "Tigers' powerful legs and retractable claws make them excellent leapers, swimmers and climbers. However, tigers are not built for extensive movements. They have to stalk near their prey to hunt them down because they can't run long distances"},
    {id: cuid(),
    question: "What is being communicated when a tiger's tail whips from side to side?",
    correctAnswer: "Aggression",
    answers: ["Aggression","Playfulness", "Sexual receptivity", "Relaxation"],
    feedback: "Like house cats, the position of a tiger's tail conveys its mood. A relaxed tiger has is tail hung loosely. A wagging or twitching tail indicates aggression. Tigers on the prowl rapidly moves its tail from side to side with occasional twitches."},
    {id: cuid(),
    question: "Why do tigers leave scratch marks on tree trunks?",
    correctAnswer: "To mark their territory",
    answers: ["To mark their territory","To strengthen their leg muscles", "To attract prey", "All of those above"],
    feedback: "Secretions from glands in the feet leave deposits which are easily smelled by other tigers. For experts the height of claw marks on trees is an indicator of the tiger's size."},
    {id: cuid(),
    question: "Which tiger subspecies is the biggest?",
    correctAnswer: "Siberian",
    answers: ["Bengal", "Siberian","Indochinese", "Sumatran"],
    feedback: "Siberian Tigers are the biggest tiger breed in the world. Siberian Tigers are the biggest of all the tigers and they usually weigh around 500 to 600+ pounds on average. "},
    {id: cuid(),
    question: "Which of the following is true of tigers?",
    correctAnswer: "Tigers are the only wild cats with stripes and no spots",
    answers: ["Tigers are the only wild cats that swim", "Tigers are the only wild cats with stripes and no spots","They are the smallest of all big cats", "All of the above"],
    feedback: "Line a tiger up with his wild cousins and you will notice that he's the only one that has stripes. Jaguars, leopards, cheetahs have spots, while lions are mostly solid colors."},
    {id: cuid(),
   question: "A tiger's stripes are?",
    correctAnswer: "Unique, like human fingerprints",
    answers: ["Similar to others of its species", "Identical only to family units", "Unique, like human fingerprints","Similar to those of other wild cats'"],
    feedback: "No two tigers have the same pattern of stripes!"},
    {id: cuid(),
    question: "Tigers live in the wild only in?",
    correctAnswer: "Asia",
    answers: ["Asia","Asia and Africa", "Africa", "Europe and Asia"],
    feedback: "Tigers are indigenous only to the continent of Asia."},
]